...clazyfaction

diff --git a/.github/actions/clazy/action.yml b/.github/actions/clazy/action.yml
--- a/.github/actions/clazy/action.yml
+++ b/.github/actions/clazy/action.yml
@@ -80,6 +80,12 @@ inputs:
     description: |-
       Is used to check only modified and appended files.
     default: ""
+  fail-on-warnings:
+    description: |
+      Fail with error code, when warnings were found too
+    required: false
+    default: false
+
 outputs:
   WARNINGS_COUNT:
     description: 'Total warnings count'
@@ -153,10 +159,16 @@ runs:
         CLAZY_CHECKS_AS_ERRORS: ${{ inputs.warnings_as_errors }}
         IGNORE_HEADERS : ${{ inputs.ignore-headers }}
         ONLY_DIFF: ${{ inputs.only-diff }}
+        FAIL_ON_WARNINGS: ${{ inputs.fail-on-warnings }}
       run: |
         PATH=~/.local/clazy/bin:$PATH "$GITHUB_ACTION_PATH/clazy.sh"
 
     - name: Exit if error
-      if: ${{steps.clazy-check.outputs.ERRORS_COUNT > 0 || steps.clazy-check.outputs.WARNINGS_COUNT > 0 }}
+      if: ${{steps.clazy-check.outputs.ERRORS_COUNT > 0 || (inputs.fail-on-warnings && steps.clazy-check.outputs.WARNINGS_COUNT > 0) }}
       shell: bash
-      run: exit 1
+      env:
+          ERRORS: ${{ steps.clazy-check.outputs.ERRORS_COUNT }}
+          WARNINGS: ${{ steps.clazy-check.outputs.WARNINGS_COUNT }}
+      run: |
+        echo "::debug::Clazy resulted in $ERRORS errors and $WARNINGS warnings"
+        exit 1
