next try

diff --git a/.github/workflows/gonnect.yml b/.github/workflows/gonnect.yml
--- a/.github/workflows/gonnect.yml
+++ b/.github/workflows/gonnect.yml
@@ -49,6 +49,7 @@ jobs:
       - name: Static code analysis
         uses: whisperity/codechecker-analysis-action@v1
         with:
+          version: '6.24.4'
           logfile: ${{ github.workspace }}/Build/compile_commands.json
 
   clazy:
@@ -84,12 +85,21 @@ jobs:
         run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
       - name: Clazy action
+        id: clazy
         uses: MinyazevR/clazy-standalone-action@v0.2.1
         with:
           install-stable: true
           ignore-dirs: '(.*qmltyperegistrations.*|.*/tests/.*|.*/\\.rcc/.*)'
           checks: level0,level1,qt6-header-fixes,no-no-module-include,no-lambda-unique-connection
-          warnings_as_errors: unused-value,warnings,macro-redefined,writable-strings,return-type,null-conversion,pragma-system-header-outside-header,implicit-function-declaration
+          warnings_as_errors: level0,level1,qt6-header-fixes,no-no-module-include,no-lambda-unique-connection
+
+      - name: "Fail the job if new findings are introduced"
+        if: ${{ steps.clazy.outputs.errors-count > 0 }}
+        shell: bash
+        run: |
+          echo "::error title=Clazy analysis errors::Analysed commit would introduce new clazy analysis errors and potential bugs to the project"
+          # Fail the build, after results were collected and uploaded.
+          exit 1
 
   tests:
     runs-on: ubuntu-latest
